### ISSUE TITLE
[ERROR] mysql : [ERROR] Found option without preceding group in config file

### ISSUE THREAD

**Issue by Titeuf49** [poppabear8883/UNIT3D-INSTALLER#1]
Hello, first of all thank you for your work.
I have an error message while creating the database:
"[ERROR] mysql : [ERROR] Found option without preceding group in config file
        /root/.my.cnf at line 1!
        mysql: [ERROR] Fatal error in defaults handling. Program aborted!"
In advance, thank you for your reply
Titeuf

**Comment by poppabear8883** [comment]
Please give me more information regarding your OS and Environment. Also please try again with a Fresh OS and the latest Clone of this repository.

Please remember this is in its very early stages of development ...

**Comment by poppabear8883** [comment]
I have have in-fact been able to reproduce this issue.

**Comment by poppabear8883** [comment]
Confirmed the above commit fixed this issue
