### ISSUE TITLE
The environment file is invalid: Dotenv values containing spaces must be surrounded by quotes.

### ISSUE THREAD

**Issue by JohnyBeGood** [poppabear8883/UNIT3D-INSTALLER#13]
Hello,

Everything appeared to be installed without any issue on my server and right after did reboot of the server and I'm getting this when I visit server address:
`The environment file is invalid: Dotenv values containing spaces must be surrounded by quotes.`
This is on fresh copy of Ubuntu server 18.04.1

**Comment by poppabear8883** [comment]
interesting, can you post the `.env` file here ? 

**BE SURE TO USE `*`'s TO REMOVE SENSITIVE DATA**

**Comment by JohnyBeGood** [comment]
Sure. Please advise where that file is located?

**Comment by poppabear8883** [comment]
it is in your `project root` which is likely `/var/www/html`

**Comment by JohnyBeGood** [comment]
Got it. Here we go:

```
APP_ENV=prod
APP_KEY=
APP_DEBUG=false
APP_URL=http://bt.tld.com

LOG_CHANNEL=daily

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=**********
DB_DATABASE=unit3d
DB_USERNAME=myusername
DB_PASSWORD=**********

BROADCAST_DRIVER=redis
CACHE_DRIVER=redis
SESSION_DRIVER=redis
SESSION_LIFETIME=120
QUEUE_DRIVER=database

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379
REDIS_DEFAULT_DB=0
REDIS_SESSION_DB=1

MAIL_DRIVER=smtp
MAIL_HOST=localhost
MAIL_PORT=25
MAIL_USERNAME=myusername
MAIL_PASSWORD=**********
MAIL_ENCRYPTION=TLS
MAIL_FROM_NAME=My Test
MAIL_FROM_ADDRESS=mysystemuser

DEFAULT_OWNER_NAME=myusername
DEFAULT_OWNER_EMAIL=myemail@yahoo.com
DEFAULT_OWNER_PASSWORD=**********

TMDB_API_KEY=45478
OMDB_API_KEY=43434
```

**Comment by poppabear8883** [comment]
The issue is this `MAIL_FROM_NAME=My Test` 

**(Note the space after My)**

This is in-fact an issue with the installer and should be fixed.

Related issue #5 

I am marking this as a `critical bug` and will commit a fix asap.

**I'm also noticing you don't have a `APP_KEY` ?**

**Comment by JohnyBeGood** [comment]
How will I know when its fixed and how can I update it?

No, I did not enter real APP_KEY because I just wanted to install.

**Comment by poppabear8883** [comment]
This issue will be closed when its been fixed.

You can manually edit the file and just remove the `space` from `MAIL_FROM_NAME=My Test`

Like this `MAIL_FROM_NAME=MyTest`

And you will want to make sure you have a `APP_KEY`

You can generate one by running this command `cd /var/www/html && php artisan key:generate`

Taking care of those things should fix your issues in regards to the `.env` file.

**Comment by JohnyBeGood** [comment]
Got it.

Lets say if I wanted to wait for the fix what command would I use to pull new updated files,
would I just clone GitHub Repository using this command `git clone https://github.com/ServNX/UNIT3D-INSTALLER.git` ?

For some reason it does not want to generate?

```
user@bt:/var/www/html$ sudo cd /var/www/html && php artisan key:generate
[sudo] password for user:
sudo: cd: command not found
user@bt:/var/www/html$ cd /var/www/html
user@bt:/var/www/html$ ls
app                 composer.json      _config.yml        laravel-echo-server.json  package-lock.json  resources   todo.php
artisan             composer.lock      CONTRIBUTING.md    LICENSE                   phpunit.xml        routes      vendor
bootstrap           composer-setup.sh  database           node_modules              public             server.php  webpack.mix.js
CODE_OF_CONDUCT.md  config             ISSUE_TEMPLATE.md  package.json              README.md          storage
user@bt:/var/www/html$ php artisan key:generate
Could not open input file: artisan
user@bt:/var/www/html$

```

**Comment by poppabear8883** [comment]
Yes you can re-clone the repository 
**OR**
Just go into the repository you have already cloned and run `git pull origin master`

As per your other issue `cd /var/www/html && sudo php artisan key:generate`

**Comment by JohnyBeGood** [comment]
Got it.

With that command I was able to generate `APP_KEY`

So I've made changes and renamed it to **MAIL_FROM_NAME=MyTest** but now when I try to open bt.mydomain.com it redirects to bt.mydomain.com/login
and displayes standard browser error


This page isn’t working
bt.tld.com is currently unable to handle this request.
HTTP ERROR 500

**Comment by poppabear8883** [comment]
Your new issue is unrelated to this issue. Please visit the discord server and seek general support in the `#support` channel.

**Comment by JohnyBeGood** [comment]
Ok, what's the discord server address? Can't find it anywhere.

**Comment by poppabear8883** [comment]
https://discord.gg/Yk4NBUU

**Comment by JohnyBeGood** [comment]
Thanks!
