### ISSUE TITLE
[v1.0-Beta.8] Force SSL Usage

### ISSUE THREAD

**Issue by HDVinnie** [poppabear8883/UNIT3D-INSTALLER#14]
In my opinion its 2018 and we shouldn't even give the end-user a option to NOT use SSL.

**Comment by poppabear8883** [comment]
I'm wondering however if this is a sane thing to do. What if in very special cases that a user doesn't want to use SSL for whatever reason ?

**Comment by HDVinnie** [comment]
I guess. I can't think of one reason to not use SSL. Specially when comes to running a tracker.

**Comment by poppabear8883** [comment]
Yea i see your point and i do agree ..

**Comment by owenvoke** [comment]
Could use SSL as the default, but have a flag such as `--disable-ssl` that stops it being used if the user wants it?

**Comment by poppabear8883** [comment]
that's exactly what i was planning on doing ... ;)

**Comment by poppabear8883** [comment]
@HDVinnie if you want to take care of this issue then we can release `v1.0-Beta.8`

**Comment by OlafvdSpek** [comment]
What about a dev server on localhost or localnet? Self-signed certs might be an option but Chrome makes it hard to accept them as far as I know.
