### ISSUE TITLE
debian 9 install not work

### ISSUE THREAD

**Issue by erwieder** [poppabear8883/UNIT3D-INSTALLER#18]
user@xxxxx: git clone .....
user@xxxxx: cd installer
user@xxxxx/installer: ./install.sh
user@xxxxx/installer: 

nothing happens :/

**Comment by HDVinnie** [comment]
So you ran:

```
git clone https://github.com/poppabear8883/UNIT3D-INSTALLER.git installer
cd installer
sudo ./install.sh
```

On a FRESH server with nothing on it but a new install of Debian 9?

**Comment by erwieder** [comment]
fresh Debian 9 with nginx and php.

with sudo ./install.sh  the same thing

**Comment by poppabear8883** [comment]
@erwieder I will look in to this shortly.

In the mean time if you could give me some more information on what your setup looks like that will help me.

- Dedicated or VPS ?
- Server Specs ? CPU ? Ram ? Disk ?
- OS ?
- Official OS Download or Template OS from a provider ?
- Fresh Install ? Nothing else, this includes `nginx` & `php` ? No control panels ?

**Comment by m333w** [comment]
Same here : 

`root@p2p:/opt/installer# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
root@p2p:/opt/installer#`

Fresh install, with nothing runing. LXC with 4bg ram, 4vcore of Intel Xeon E5-1630v3, 80GB disk space. Template from here : http://download.proxmox.com/images/system/

Best regards.

**Comment by m333w** [comment]
And now a fresh install of ubuntu 18.04

`root@p2p:~# cd /opt/
root@p2p:/opt# git clone https://github.com/poppabear8883/UNIT3D-INSTALLER.git installer
Cloning into 'installer'...
remote: Enumerating objects: 41, done.
remote: Counting objects: 100% (41/41), done.
remote: Compressing objects: 100% (34/34), done.
remote: Total 303 (delta 17), reused 14 (delta 5), pack-reused 262
Receiving objects: 100% (303/303), 60.59 KiB | 646.00 KiB/s, done.
Resolving deltas: 100% (145/145), done.
root@p2p:/opt# cd installer
root@p2p:/opt/installer# sudo ./install.sh


 Preparing Environment For The Installer ...
=============================================

 Adding PPA Repositories ...
 Error: Adding ppa:nginx/development Failed!
 Please try re-running the script via 'sudo ./install.sh'
root@p2p:/opt/installer# sudo ./install.sh`

**Comment by HDVinnie** [comment]
@m333w in your case for ubuntu 18.04 use dev branch

```
git clone https://github.com/poppabear8883/UNIT3D-INSTALLER.git installer
cd installer
git checkout dev
sudo ./install.sh
```

**Comment by m333w** [comment]
Install begin ! thx :)

**Comment by m333w** [comment]
The install fail because the srcipt try to registre `www` with certbot. I prefere use personnal cert, hoow i can make an install without ssl certbot ?

The install gona be on a subdomain allready, i have registe a new pointer with www.p2p.domain.tld just to make an install to test. If its work can i delete after the `www` ?

**Comment by poppabear8883** [comment]
Closing due to no response from the original OP. @m333w if you are still receiving issues please open a separate issue here on GitHub.
