### ISSUE TITLE
[Suggestion] add web open free control panel

### ISSUE THREAD

**Issue by ghost** [poppabear8883/UNIT3D-INSTALLER#20]
add this intaller install with unit3d (user can install or no ) web open free control panel like isp, webmin or other

**Comment by poppabear8883** [comment]
Not sure that I'm following your suggestion

**Comment by ghost** [comment]
sorry for my bad english what did you understand?

**Comment by poppabear8883** [comment]
Not really understanding anything. 

Either you are asking to add an option to install unit3d into webmin or ispconfig.

OR

You want a way to install unit3d FROM ispconfig or webmin ...

Either way this isnt something I plan on doing in the near future.

**Comment by ghost** [comment]
yes add an option to intall unit3d into webmin or ispconfig.

**Comment by HDVinnie** [comment]
I don't think this is wise. No need to over complicate this installer.
