### ISSUE TITLE
After update from 1.8.5 to 1.8.6 Staff Dashboard shows update available 

### ISSUE THREAD

**Issue by JohnyBeGood** [poppabear8883/UNIT3D-INSTALLER#24]
Did update to 1.8.6 with `php artisan git:update` and it went well. When I went to Staff Dashboard it was showing 1.8.5 was installed and that there's 1.8.6 available. Per xI Poppabear `config/unit3d.php` was never updated. Running `git fetch origin && git checkout origin/master -- config/unit3d.php` fixed the issue.

**Comment by poppabear8883** [comment]
This is my bad, I know i said to open this issue here, but it should had been done on the main repository.
