### ISSUE TITLE
[v1.0-Beta.8] Handle systems with non-UTF-8 locales

### ISSUE THREAD

**Issue by poppabear8883** [poppabear8883/UNIT3D-INSTALLER#25]
This is not a bug, but maybe this issue should be handled automatically if the locale is non-UTF8 ?

Ref issue https://github.com/oerdnj/deb.sury.org/issues/56#issuecomment-93694233

**Comment by HDVinnie** [comment]
A JFYI. Used dev branch for a sever that suffered being non-UTF-8. Everything went great!

**Comment by poppabear8883** [comment]
This is great news .. Thank you for reporting!
