### ISSUE TITLE
[v1.0.0] certbot renew fails..

### ISSUE THREAD

**Issue by gjm1976** [poppabear8883/UNIT3D-INSTALLER#29]
certbot renew --dry-run
[===░░░░░░░░░░░░░░░░░░░░░░░░░] (Please Wait ...)
In Process.php line 1160:

  The process "certbot renew --dry-run" exceeded the timeout of 180 seconds.

install

**Comment by poppabear8883** [comment]
Please try and do a fresh OS install and lunch the installer again. If it still fails please provide details about your environment.

**Comment by HDVinnie** [comment]
I have noticed this a few times myself even when not using installer. Im 99% confident there is nothing we can do about it besides add a check in place where if the `dry-run` process fails we just spit out a warning and continue with installer instead of killing it.

**Comment by poppabear8883** [comment]
@HDVinnie if you want to handle that then i'm ok with it. Otherwise, i'll have to do it sometime over the next few days.

**Comment by HDVinnie** [comment]
@poppabear8883 Ill see what I can do. Thanks.

**Comment by poppabear8883** [comment]
@gjm1976 If you could **After The Error** run `certbot renew --dry-run` manually and paste here the output you receive from it.
