### ISSUE TITLE
No debian.sh

### ISSUE THREAD

**Issue by TTsWeb** [poppabear8883/UNIT3D-INSTALLER#30]
I might be blind, but I dont see debian.sh in this source to install it?

**Comment by poppabear8883** [comment]
You are not looking for `debian.sh` you should be installing using the `install.sh` script

**Comment by TTsWeb** [comment]
what ever i see this script is only for ubuntu.
from install.sh
            "Debian")
                echo 'Debian GNU/Linux \n \l' > /etc/issue
                type='debian'
                break
then later...........
if [ -e $type.sh ]; then
    bash ./$type.sh
fi

Without that file cant be installed period on debian based systems so you should remove it could be and put ONLY FOR UBUNTU!!
