### ISSUE TITLE
PHP Fatal error: require(): Failed opening required '/var/www/html/vendor/autoload.php'

### ISSUE THREAD

**Issue by f1she3** [poppabear8883/UNIT3D-INSTALLER#31]
Hello,
I downloaded the installer on a fresh install of Ubuntu 16.04.4, everything went well during the install process, but once it's finished my unit3d instance doesn't display CSS, and this warning / error is shown on the supervisor logs of unit3d-queue:unit3d-queue_00 and unit3d-queue:unit3d-queue_01 : 

`PHP Warning:  require(/var/www/html/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/artisan on line 1` then  `PHP Fatal error:  require(): Failed opening required '/var/www/html/vendor/autoload.php' (include_path='.:/
usr/share/php') in /var/www/html/artisan on line 18` (Warning then error)

Do you have any idea ? 
Thanks

EDIT : I tried again this time with a domain name and choosing HTTPS, the server is running, but the error is still there

**Comment by silez** [comment]
> No such file or directory .... artisan

is the file "artisan" in your /var/www/html folder or is the path wrong? :)

**Comment by f1she3** [comment]
No the path is correct, but the error disappeared.
 I did nothing on my server except updating it, so maybe we can close this issue if for now ?

**Comment by poppabear8883** [comment]
I am working on a new installer (A stable version), its undergoing an entire rewrite. So for now, we will close this issue.
