### ISSUE TITLE
su www-date -s /bin/bash --command="cd /var/www/html && nmp install"

### ISSUE THREAD

**Issue by sammeepay** [poppabear8883/UNIT3D-INSTALLER#32]
su www-date -s /bin/bash --command="cd /var/www/html && nmp install"

Error help me please!!
![unit3d_error](https://user-images.githubusercontent.com/13168156/56634809-83d97800-668d-11e9-98b8-159db4279903.jpg)

**Comment by HDVinnie** [comment]
duplicate to https://github.com/poppabear8883/UNIT3D-INSTALLER/issues/35
