### ISSUE TITLE
MySQL Triggers Installation error & terminates

### ISSUE THREAD

**Issue by c-hew** [poppabear8883/UNIT3D-INSTALLER#33]
### Issue Type
- [x] Technical Discussion
- [x] Question

### End User Info
-- UNIT3D Version: Latest 
-- Laravel Version: Latest
-- PHP Version: 7.2

-- Database Driver & Version:
MySQL, Latest
-- Web Server Driver & Version:
Latest
-- OS Driver and Version:
Ubuntu 19.04
Ubuntu 18.04

### Actual Behavior:
Automated installer terminates with MySQL "data directory needs to be specified"

18.04 Behaviour: 
mysqladmin: [Warning] Using a password on the command line interface can be
insecure.
Warning: Since password will be sent to server in plain text, use ssl connection
to ensure password safety.

### Steps To Reproduce The Problem:
1. Doing sudo ./install.sh again
2. Running through unskippable questions
3.

### Possible Fix:
Resumes to install when installer terminates instead of running the whole process again.

**Comment by HDVinnie** [comment]
I see you using Ubuntu 19.04. Installer readme cleary states it supports 16.04 and 18.04 at the time. Have you tried it with one of those versions?

**Comment by c-hew** [comment]
It terminates with

mysqladmin: [Warning] Using a password on the command line interface can be
         insecure.
         Warning: Since password will be sent to server in plain text, use ssl connection
         to ensure password safety.
on 18.04

Tried on both my virtual machine and SSH.
