### ISSUE TITLE
MySQL Create User failed during installation

### ISSUE THREAD

**Issue by timguy99** [poppabear8883/UNIT3D-INSTALLER#34]
Getting an error that it cannot create the unit3d MySQL user during installation. I tried now 3 times with different passwords etc.

Ubuntu 18.04.2 LTS

Is there any way to proceed or anything I can look at to debug?

Also, I tried joining the Discord that is advertised here but it doesn't seem to exist.

![Screen Shot 2019-07-05 at 11 30 24 AM](https://user-images.githubusercontent.com/44981994/60732567-612ecf80-9f18-11e9-8678-3d49b4e07d65.png)

**Comment by HDVinnie** [comment]
Not able to replicate. 

https://discord.gg/ntnPxzG is the discord.
