### ISSUE TITLE
Excedeed Timeout

### ISSUE THREAD

**Issue by PanjiNamjaElf** [poppabear8883/UNIT3D-INSTALLER#35]
I try to install UNIT3D use automate installer on my VirtualBox - Ubuntu Server
but when run command "su www-data -s /bin/bash --command="cd /var/www/html && npm run prod""

The time is exceeded...
What i must do ?

**Comment by poppabear8883** [comment]
did you try running the command manually

`su www-data -s /bin/bash --command="cd /var/www/html && npm run prod"`

**Comment by poppabear8883** [comment]
if that completes successfully, run the follow comands in this order:

`su www-data -s /bin/bash --command="cd /var/www/html && php artisan key:generate"`
`su www-data -s /bin/bash --command="cd /var/www/html && php artisan migrate --seed"`
`su www-data -s /bin/bash --command="cd /var/www/html && php artisan test:email"`

After those complete you should be good to go ...

Just fyi you can find these commands in the source, it helps you understand whats happening behind the scenes (click link below) ...

https://github.com/poppabear8883/UNIT3D-INSTALLER/blob/master/src/Installer/UNIT3D/Unit3dSetup.php#L127

**Comment by PanjiNamjaElf** [comment]
> did you try running the command manually
> 
> `su www-data -s /bin/bash --command="cd /var/www/html && npm run prod`

i run this command not run.. is display " > " on next command it mean still not finish.

![image](https://user-images.githubusercontent.com/16651293/63231212-b01f9280-c242-11e9-816c-9a89b8740077.png)

**Comment by PanjiNamjaElf** [comment]
Miss double quote in last string :D

**Comment by poppabear8883** [comment]
my bad, i'll edit that

**Comment by PanjiNamjaElf** [comment]
Can i rename domain name manually ?
how to do it?

**Comment by PanjiNamjaElf** [comment]
![image](https://user-images.githubusercontent.com/16651293/63232396-c8e37480-c251-11e9-9985-8e3b982860fc.png)

its look like this so messy :/

**Comment by poppabear8883** [comment]
did you run `su www-data -s /bin/bash --command="cd /var/www/html && npm run prod"`

**Comment by PanjiNamjaElf** [comment]
i try it from begin again and success only mail display warning because on virtualbox

![image](https://user-images.githubusercontent.com/16651293/63232437-368fa080-c252-11e9-8ab9-6a751335f6c0.png)

**Comment by PanjiNamjaElf** [comment]
Authentication failure :/
![image](https://user-images.githubusercontent.com/16651293/63232453-5aeb7d00-c252-11e9-81ec-16059d3268c3.png)
