### ISSUE TITLE
Problem with HTTP only (for debugging with tcpdump)

### ISSUE THREAD

**Issue by StuartRothrock** [poppabear8883/UNIT3D-INSTALLER#40]
I realize SSL is the only way to use in a production/public environment. However I installed it, with the installer, in a test/debug private environment and it still redirects to HTTPS after logging in. Where do I need to disable this redirection? Thanks.

**Comment by HDVinnie** [comment]
The UNIT3D automated installer is meant to get a HTTPS instance of UNIT3D going for you. The SSL option will be removed and HTTPS only allowed in future. For local dev you should be using something like Homestead. If your using a VPS or alike with a valid name why did you not pick HTTPS as its free certs and does it all for you.....anyway read this https://github.com/HDInnovations/UNIT3D-Community-Edition#-computer-installation
