### ISSUE TITLE
Database DROP

### ISSUE THREAD

**Issue by samsepiol59** [poppabear8883/UNIT3D-INSTALLER#41]
Hi everyone, so I want to apologise right away because I don't have the exact error message on me - we had a power outage last night and I lost the terminal page... Anyway, the error was along the line of "database DROP didn't work/wasn't possible because it doesn't exist" or something very close to that.

It was the only error too, 192.168.1.99 took me to the login page but I got an error when logging in (the /login page didn't exist apparently).

**Comment by HDVinnie** [comment]
That database drop error is normal on some installs and can be ignored. So what exactly is happening when you visit your domain and try to login?

**Comment by samsepiol59** [comment]
This is what I see when I visit the IP ![image](https://user-images.githubusercontent.com/34254280/67770036-d8ebb180-fa55-11e9-8ed2-2424355f06f3.png), while this
![image](https://user-images.githubusercontent.com/34254280/67770121-0a647d00-fa56-11e9-8895-dd0537386595.png) is what happens when I try to login..!

**Comment by HDVinnie** [comment]
Why don't you have a domain? Are you running this locally? The installer is not meant for that.

**Comment by samsepiol59** [comment]
This was just a try yeah - I do have a couple of domains... I set tracker.mydomain.com in the installation process, if I point tracker.mydomain.com to my laptop's IP:port it should work then?

**Comment by HDVinnie** [comment]
If your trying to install this on your laptop for `dev` testing then you should be using something like Homestead and not this installer. This installer is for being used on like a VPS or Dedicated Server where you have nothing but a fresh install of **Ubuntu** 16 or 18 on it and a valid domain pointing to that servers IP.

**Comment by samsepiol59** [comment]
Done that (VPS with fresh ubuntu 18.04 + tracker.domain.com (A record, tracker host, pointing to the vps' IP)) but I'm getting the same exact error... database drop.

I'm not setting the email up correctly - could that have something to do with it?

**Comment by HDVinnie** [comment]
1) Why are you using a sub domain?
2) Did you select HTTPS during the installer?

**Comment by HDVinnie** [comment]
Inactive
