### ISSUE TITLE
Installer completes fine DB Connect Errors and 500 error

### ISSUE THREAD

**Issue by cryptorrents** [poppabear8883/UNIT3D-INSTALLER#43]
Installed on a clean Ubuntu 18.04 VM (kvm) and install went fine. On visiting the URL tosses a 500 error.

/var/log/nginx/error.log shows:

`root@cryptorrents:/var/www/html# tail -f /var/log/nginx/error.log
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(327): Doctrine\DBAL\Driver\PDOConnection->prepare('select `id`, `n...')
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(658): Illuminate\Database\Connection->Illuminate\Database\{closure}('select `id`, `n...', Array)
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(625): Illuminate\Database\Connection->runQueryCallback('select `id`, `n...', Array, Object(Closure))
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(334): Illuminate\Database\Connection->run('select `i...PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'unit3d.pages' doesn't exist in /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:61
Stack trace:
#0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(61): PDO->prepare('select `id`, `n...', Array)
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(327): Doctrine\DBAL\Driver\PDOConnection->prepare('select `id`, `n...')
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(658): Illuminate\Database\Connection->Illuminate\Database\{closure}('select `id`, `n...', Array)
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(625): Illuminate\Database\Connection->runQueryCallback('select `id`, `n...', Array, Object(Closure))
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(3`

Before this is was complaining about the connect to unit3d@localhost being denied, I went in and manually set the users pass in Mysql to match what the script reported at end of install and it seems to have cleared that issue up.

**Comment by HDVinnie** [comment]
Sounds like maybe the migrations failed to run. `php artisan migrate:fresh --seed` is what you can run via terminal in project root.

**Comment by cryptorrents** [comment]
Yep, that was it. Thanks!
