### ISSUE TITLE
Backspace doesn't work during Setup

### ISSUE THREAD

**Issue by OlafvdSpek** [poppabear8883/UNIT3D-INSTALLER#46]
```
 Server Name [ubuntu]:
 > ubun^H^H^H^[[3~^[[3~^H^H^H

 The FQDN for this server [ubuntu]:
 > http://^H^H^H^H^H^H^H^H
```

**Comment by HDVinnie** [comment]
Whats are you using? Im on `MacOS 10.14.6` using Hyper Terminal and backspace works fine.

Also FQDN should not contain `http:// or https:// or www.`. Should simple be like `unit3d.site`

**Comment by OlafvdSpek** [comment]
SecureCRT on Windows

**Comment by HDVinnie** [comment]
Ok I don't use Windows so will have to see if someone else can test as well.

**Comment by OlafvdSpek** [comment]
> Also FQDN should not contain `http:// or https:// or www.`. Should simple be like `unit3d.site`

I know.. but Backspace wasn't working. :p

Can't server name be derived from FQDN BTW?
