### ISSUE TITLE
Install Debian 9 - Nothing happen

### ISSUE THREAD

**Issue by karibuTW** [poppabear8883/UNIT3D-INSTALLER#54]
Hi there,
I'm using a dedicated server with Debian 9.
On a fresh install doing:
git clone https://github.com/poppabear8883/UNIT3D-INSTALLER.git installer
cd installer
sudo ./install.sh

give nothing. it seems the script don't run at the end.

is it because Debian 9 is not supported?
The install.sh is supposed to detect it is Debian, then run the debian.sh (But no debian.sh)

Thank you

**Comment by HDVinnie** [comment]
Officially Supported OS's

Ubuntu 16.04 LTS
Ubuntu 18.04 LTS

**Comment by karibuTW** [comment]
Clear,
Will be good to remove Debian 7+ (Except if tested) as even unofficially, it will not work.

I will test on ubuntu then.

Big thanks
