### ISSUE TITLE
Installer for Ubuntu 20.04

### ISSUE THREAD

**Issue by loudyin1** [poppabear8883/UNIT3D-INSTALLER#56]
Hi,
trying fresh install on vps ubuntu 20.04 keep getting this error:
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
any help welcome
cheers Loud

**Comment by HDVinnie** [comment]
More info needed. You formatted vps? Installed Ubuntu 20.04 with nothing else. No cpanel or anything. Then ran
```
git clone https://github.com/poppabear8883/UNIT3D-INSTALLER.git installer
cd installer
sudo ./install.sh
```

**Comment by loudyin1** [comment]
> More info needed. You formatted vps? Installed Ubuntu 20.04 with nothing else. No cpanel or anything. Then ran
> 
> ```
> git clone https://github.com/poppabear8883/UNIT3D-INSTALLER.git installer
> cd installer
> sudo ./install.sh
> ```

no cpanel fresh install on vps  Elite 8-32-320 of 20.04 had it working same setup on 18.04, I never got the error but still learning so hope you can help.

**Comment by HDVinnie** [comment]
Where/when are you getting the error. I can install on a digital ocean droplet using Ubuntu 20.04 just fine.

**Comment by loudyin1** [comment]
chmod 600 /root/.my.cnf
[░░░░░░░░░░░░░░░░░░░░░░░░░░░░] (Done!)
mysql -e "DROP USER IF EXISTS XXX"
[░░░░░░░░░░░░░░░░░░░░░░░░░░░░] (Done!)
mysql -e "DROP DATABASE IF EXISTS XXX"
[░░░░░░░░░░░░░░░░░░░░░░░░░░░░] (Done!)
mysql -e "CREATE DATABASE XXX"
[░░░░░░░░░░░░░░░░░░░░░░░░░░░░] (Done!)
mysql -e "CREATE USER 'XXX'@'localhost' IDENTIFIED BY 'pass';"
[░░░░░░░░░░░░░░░░░░░░░░░░░░░░] (Done!)
mysql -e "GRANT ALL PRIVILEGES ON XXX . * TO 'XXX'@'localhost'"
[░░░░░░░░░░░░░░░░░░░░░░░░░░░░] (Done!)
mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'pass'"
[░░░░░░░░░░░░░░░░░░░░░░░░░░░░] (Done!)
mysql -e "DELETE FROM mysql.user WHERE User=''"
[============================] (Done!)

 [ERROR] ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)

this is what I get logged in as ubuntu or as root still same error. removed username & pass & db name

**Comment by HDVinnie** [comment]
Are you running the installer with root account?

**Comment by loudyin1** [comment]
tried it as root & as sudo ubuntu user

**Comment by HDVinnie** [comment]
> tried it as root & as sudo ubuntu user

When you say this you mean you formatted server each time trying both accounts. 

As it seems to be failing for you at `DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')` which means there's def a permission issue. 

Not using any special characters in your db password?

**Comment by loudyin1** [comment]
> > tried it as root & as sudo ubuntu user
> 
> When you say this you mean you formatted server each time trying both accounts. **<<Yes it was reset formatted for each**
> 
> As it seems to be failing for you at `DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')` which means there's def a permission issue.
> 
> Not using any special characters in your db password?   **<< yes I have will try with them removed**
I'll reset the vps & try that.

**Comment by HDVinnie** [comment]
Yes make sure you reset the VPS to fresh and then run installer as root....then dont use special characters. Installer has an issue with them.

**Comment by loudyin1** [comment]
special characters in your db password was the issue 😂😂😂
Cheers bud 👍👍

**Comment by HDVinnie** [comment]
No problem
