### ISSUE TITLE
MySQL v8 - query cache is deprecated

### ISSUE THREAD

**Issue by k-304** [poppabear8883/UNIT3D-INSTALLER#59]
query cache is deprecated since MySQL v8:
[https://dev.mysql.com/doc/refman/5.7/en/query-cache.html](https://dev.mysql.com/doc/refman/5.7/en/query-cache.html)

This causes the MySQL Server to fail on service start.

**Comment by HDVinnie** [comment]
What does query cache have to do with this installer?

**Comment by k-304** [comment]
if i got that right, it sets this option in the my. cnf file, doesnt it?

Sent from mobile

________________________________

**Comment by HDVinnie** [comment]
ah yes the `query_cache_size` in the cnf.

**Comment by k-304** [comment]
exactly, what do u suggest since its deprecated?

Sent from mobile

________________________________

**Comment by HDVinnie** [comment]
it just needs to be removed from the config
