### ISSUE TITLE
Mailer Settings

### ISSUE THREAD

**Issue by HDVinnie** [poppabear8883/UNIT3D-INSTALLER#6]
It would be nice if the installer handled setting up the MAIL info within the `.env` like it does for the API keys. 

**Mail Settings (Used for things like invites, registration, ect.)**
`/* You will need a provider like torguard. https://torguard.net/anonymous-email.php */`

```
MAIL_DRIVER=smtp
MAIL_HOST=stealth.tg
MAIL_PORT=587
MAIL_USERNAME=example@stealth.tg
MAIL_PASSWORD=mypassword
MAIL_ENCRYPTION=TLS
MAIL_FROM_NAME=SITENAMEHERE
MAIL_FROM_ADDRESS=example@stealth.tg
```

Mail settings test should ask for following info above and if possible fire a test email to make sure it works before moving to next step.

To accomplish that we could add a simple artisan command to test the Laravel mail configuration.

**Comment by poppabear8883** [comment]
You should remember that this installer is independent from Laravel and doesn't use Laravel framework at all. Its composed of Symfony Console, Symfony Process and Bash Scripts. I had only named the bootable console application `artisan` to be consistent across both entities. 

With that said we can certainly add options for generating values in  the .env file, however i would have to see what would be involved with implementing the Laravel mail package to use for testing email settings.

If for some reason i have misunderstood your vision i apologize.

**Comment by HDVinnie** [comment]
Well Im thinking now more we add a email tester command right in UNIT3D. During the install process it asks you all the mailer fields for the `.env`. Then after installer is complete. It could THEN ask if they want to run the command i.e.: `php artisan test:email` command to test there mailer. If command runs with not error it should say something like `no error detected. please check your inbox for the test email sent to `blah@blah.com`. Otherwise if fails say `Error was detected`. Please review your `.env` and make sure your mailer configs are set properly.

**Comment by poppabear8883** [comment]
yea, certainly something we can do ... so on the Laravel side we have the `artisan` command that can run after UNIT3D is installed.

**Comment by HDVinnie** [comment]
Added the command for testing mailer. 

https://github.com/HDInnovations/UNIT3D/commit/a989584070bd6013c37dcf83aaa99dd88a394ca9

**Comment by poppabear8883** [comment]
Added in Release https://github.com/ServNX/UNIT3D-INSTALLER/tree/v1.0-beta.3

Ref Commit https://github.com/ServNX/UNIT3D-INSTALLER/commit/92afd9b39b31639c0638bd440c3393e6921e748f
