### ISSUE TITLE
fresh install on ubuntu 20.04 lts - does not setup owner user in table users

### ISSUE THREAD

**Issue by kREATUr67** [poppabear8883/UNIT3D-INSTALLER#60]
used a fresh ubuntu 20.04 install.
after the install i got 2 warnings, no error at all.

su www-data -s /bin/bash --command="cd /var/www/html && php artisan migrate --seed"
[============================] (Done!)
[Warning]

su www-data -s /bin/bash --command="cd /var/www/html && php artisan test:email"
[============================] (Done!)
[Warning]

[OK] Done!

![unit3d install v4 0](https://user-images.githubusercontent.com/67836615/97787295-702b9d80-1bb1-11eb-91be-0451d0ded84a.png)

1. the tried to login with shown login credentials, does not work, checked database table users, its empty.

2. when registering a user i got error 500, means registration has not worked.

![Sim9CzT](https://user-images.githubusercontent.com/67836615/97787445-81c17500-1bb2-11eb-93b9-0f21709828a7.png)

3. when i import a user into the database an login, same error 500

**Comment by HDVinnie** [comment]
try again. this is fixed.

**Comment by kREATUr67** [comment]
is fixed, is working, thank you very much
