### ISSUE TITLE
installing ubuntu 20

### ISSUE THREAD

**Issue by rveyn** [poppabear8883/UNIT3D-INSTALLER#61]
cp -f /root/installer/src/Helpers/../Resources/ubuntu/mysql/my-large.cnf /etc/mysql/my.cnf
[░░░░░░░░░░░░░░░░░░░░░░░░░░░░] (Done!)
mysql_install_db
[============================] (Done!)

 [ERROR] sh: 1: mysql_install_db: not found

root@

----- its end with this errors

**Comment by HDVinnie** [comment]
Some more information would be useful.....

What OS?
Was there anything preexisting on the server?
What commands did you run?
Modified OS image?

**Comment by rveyn** [comment]
Sorry for the lack of information.

**The OS:**

 Ubuntu 20.04.1

**Server eta:**

New Server fresh install

**Command:**

sudo ./install.sh

Original iso from ubuntu website

**Comment by HDVinnie** [comment]
I assume you ran
```
git clone https://github.com/poppabear8883/UNIT3D-INSTALLER.git installer
cd installer
sudo ./install.sh
```
For Ubuntu 20.04? Im not able to replicate. Are you using a minimal OS image? Does your host not provide OS Image installs?

**Comment by rveyn** [comment]
I reinstalled 20.04.1 fresh install from iso.

root@ethor:~/installer# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:    20.04
Codename:   focal


I run apt-get update, upgrade and reboot.


after reboot:


root@et:~# git clone https://github.com/poppabear8883/UNIT3D-INSTALLER.git installer
Cloning into 'installer'...
remote: Enumerating objects: 152, done.
remote: Counting objects: 100% (152/152), done.
remote: Compressing objects: 100% (111/111), done.
remote: Total 645 (delta 80), reused 65 (delta 31), pack-reused 493
Receiving objects: 100% (645/645), 113.06 KiB | 719.00 KiB/s, done.
Resolving deltas: 100% (349/349), done.
root@et:~# cd installer
root@et:~/installer# ./install.sh


 Preparing Environment For The Installer ...
=============================================

 Setting UTF8 ...
./ubuntu.sh: line 18: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8): No such file or directory
 OK

 Adding PPA Repositories ...
 OK

 Updating Packages ...
 OK

 Installing PHP ...
Extracting templates from packages: 100%
 OK

 Installing Composer ...
 OK

 Adding Installer Packages ...
 Error: Adding Installer Packages Failed!
 Please try re-running the script via 'sudo ./install.sh'
root@et:~/installer# 



thats all what I did

**Comment by HDVinnie** [comment]
Only thing I can think of is your host. I have updated the installer for latest UNIT3D but I still cannot replicate your issue on multiple hosts. Digital Ocean and SoYouStart.

**Comment by rveyn** [comment]
Thanks for your time HDVinnie.

after many os re-installation I found out the problm...


I dont know why, and how. but php7.4 and php8 got installed in same time. so /usr/sbin/php was version 7.4

so I renamed /usr/sbin/php80 to /usr/sbin/php and its worked

**Comment by rveyn** [comment]
after the install. I try to log with my username and password and I got:

Error 500: Internal Server Error!
Our server encountered an internal error.
Sorry For The Inconvenience


any idea what I sould look?
