### ISSUE TITLE
 UNIT3D tracker

### ISSUE THREAD

**Issue by denniszg** [poppabear8883/UNIT3D-INSTALLER#63]
Hello,

I installed the tracker. When I set up a torrent and drop a seed on it, the torrent shows that I am a seeder. when i want to download that torrent with a torrent client i can't. Why? I pray for help.

Kind regards,
Denis

**Comment by HDVinnie** [comment]
What does this have to do with the installer? Use the proper repo. https://github.com/HDInnovations/UNIT3D-Community-Edition
