### ISSUE TITLE
Certificate

### ISSUE THREAD

**Issue by ghost** [poppabear8883/UNIT3D-INSTALLER#64]
Got this one. Prestine 20.04 LTS ubuntu server.
Tryed 3 times. Same result.
![be07e97d614599f91344cdfa26d89026](https://user-images.githubusercontent.com/42607841/111203777-b401cb00-85c5-11eb-9b33-c9a7e2455f2b.png)

**Comment by clandestine8** [comment]
You did not provide the installer a valid FQDN. 

Localhost can not be validated by let's encrypt. Installer is designed for deployment, not testing. 

Please provide the installer a FQDN that is accessible to the world wide web and ensure the system hosting the site has a valid public IP address and you have pointed the FQDN to the IP address at the time of installation.

**Comment by ghost** [comment]
[log.txt](https://github.com/poppabear8883/UNIT3D-INSTALLER/files/6143724/log.txt)

**Comment by ghost** [comment]
> 
> 
> You did not provide the installer a valid FQDN.
> 
> Localhost can not be validated by let's encrypt. Installer is designed for deployment, not testing.
> 
> Please provide the installer a FQDN that is accessible to the world wide web and ensure the system hosting the site has a valid IP address and you have pointed the FQDN to the IP address at the time of installation.

Ok. I'll try that.

**Comment by clandestine8** [comment]
[log.txt](https://github.com/poppabear8883/UNIT3D-INSTALLER/files/6143724/log.txt)


Server Setup
==================
 The FQDN for this server [unit3d]: localhost

 Primary IP Address [192.168.1.216]:
 

`localhost` is not a valid FQDN

`192.168.1.216` is not a publically accessible IP address

**Comment by HanOddbjorn** [comment]
> 
> 
> [log.txt](https://github.com/poppabear8883/UNIT3D-INSTALLER/files/6143724/log.txt)
> # Server Setup
> 
> The FQDN for this server [unit3d]: localhost
> 
> Primary IP Address [192.168.1.216]:
> 
> `localhost` is not a valid FQDN
> 
> `192.168.1.216` is not a publically accessible IP address
