### ISSUE TITLE
Failed on installing ssl

### ISSUE THREAD

**Issue by D3monCoder** [poppabear8883/UNIT3D-INSTALLER#7]
urn:ietf:params:acme:error:connection :: The server could not connect
         to the client to verify the domain :: Fetching
http://www.domainname.com/.well-known/acme-challenge/Dgij10WefTWCrzSKX
         2W4bB-BeJa17IK2V1AiEg8ZjE4: Timeout during connect (likely firewall
         problem)
Ubuntu 18.04

**Comment by HDVinnie** [comment]
Are you using a VPS or Dedicated Server? This error likely occurs when 443 port is blocked. Please make sure that your domain name was entered correctly and the DNS A/AAAA record(s) for that domain contain(s) the right IP address. Additionally, please check that your server has a publicly routable IP address and that no firewalls are preventing the server from communicating with the
client.

**Comment by D3monCoder** [comment]
i was on a vps. reinstalled it and it worked
