### ISSUE TITLE
16.04 / 18.04 - Undefined offset: 0 - Unsupported GNU/Linux distribution - Installer Policies

### ISSUE THREAD

**Issue by Olaf1607** [poppabear8883/UNIT3D-INSTALLER#8]
During the install process steps of Validating Installer Policies this error appears on Ubuntu 16.04 and 18.04.

```
PHP Notice:  Undefined offset: 0 in /root/UNIT3D-INSTALLER/src/Helpers/helpers.php on line 133
Unsupported GNU/Linux distribution
```

**Comment by poppabear8883** [comment]
Interestingly this has been tested on both OS's and have yet to come across such an error.

Can you provide to me the output of `head -n1 /etc/issue | cut -f 2 -d ' '` on the server in question ?
